// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  try {
    const { data, error } = await client.auth.getUser();
    if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
    return { user: data.user, error: null };
  } catch (err) {
    // auth.getUser() THROWS (rather than returning a clean error
    // object) for a token it can't parse as a real user session — the
    // anon key every guest request sends is exactly this case: it's a
    // real JWT, but a project-level API key, not a user session token,
    // so it has no `sub` (user id) claim at all. That's "invalid
    // claim: missing sub claim" specifically. Treating it the same as
    // any other failed lookup — no user, not a crash — is what makes
    // every guest-checkout code path that calls this actually work.
    return { user: null, error: err instanceof Error ? err.message : 'Not authenticated' };
  }
}

// ═══ attach-my-guest-orders/index.ts (entry point) ═══
// ── attach-my-guest-orders ────────────────────────────────────────
// POST body: (none needed — acts on the authenticated caller only)
// Requires: Authorization: Bearer <user's Supabase access token>
//
// Companion to attach-guest-order (which claims one specific order by
// id, used right after signing up through that order's own
// confirmation page). This one is broader and doesn't need to know
// any order id at all: it finds every unclaimed guest order whose
// shipping_address email matches the caller's own verified account
// email, and claims all of them at once. This is what actually
// handles "I placed a guest order, then created an account totally
// separately, unrelated to that order" — the specific-order flow can
// only ever fire if someone signs up through that exact order's own
// link, so it was never going to catch this case on its own.
//
// Same authorization model as attach-guest-order: real session
// required, and only ever matches the CALLER's own verified email —
// never a bare string claim from the request body.


Deno.serve(async (req) => {
  const opt = handleOptions(req);
  if (opt) return opt;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { user, error: authError } = await getRequestUser(req);
    if (!user || !user.email) return jsonResponse({ error: authError || 'Not authenticated' }, 401);

    const accountEmail = user.email.trim().toLowerCase();
    const admin = getAdminClient();

    // Filtered in JS rather than via a Postgres-side case-insensitive
    // query — shipping_address.email is raw, unnormalized user input
    // from the checkout form (never forced to lowercase the way
    // guest_email on payment_intents is), so a case-sensitive DB-side
    // match could easily miss a real match over something as trivial
    // as capitalization. Scans every currently-unclaimed guest order;
    // fine at this store's present scale — would want pagination or a
    // dedicated index if that table grows very large.
    const { data: candidates, error: fetchError } = await admin
      .from('orders')
      .select('id, shipping_address')
      .is('user_id', null);

    if (fetchError) return jsonResponse({ error: fetchError.message }, 500);

    const matchingIds = (candidates || [])
      .filter(o => (o.shipping_address as Record<string, string> | null)?.email?.trim().toLowerCase() === accountEmail)
      .map(o => o.id);

    if (matchingIds.length === 0) return jsonResponse({ attachedCount: 0 });

    const { error: updateError } = await admin
      .from('orders')
      .update({ user_id: user.id })
      .in('id', matchingIds)
      .is('user_id', null); // re-checked at update time, closing the same race-condition gap attach-guest-order guards against

    if (updateError) return jsonResponse({ error: updateError.message }, 500);

    return jsonResponse({ attachedCount: matchingIds.length });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
