// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  const { data, error } = await client.auth.getUser();
  if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
  return { user: data.user, error: null };
}

// ═══ attach-guest-order/index.ts (entry point) ═══
// ── attach-guest-order ────────────────────────────────────────────
// POST body: { orderId: string }
// Requires: Authorization: Bearer <user's Supabase access token> —
// this is the one guest-checkout-related function that DOES hard-
// require real authentication, on purpose: it's the opposite case
// from the others. This only ever runs after someone has genuinely
// signed in, and only attaches an order to THEIR OWN account, which is
// how it satisfies the brief's explicit requirement: "Never associate
// an order merely because email strings match" / "Only attach a guest
// order to an existing account after appropriate authentication and
// verification." Matching email strings alone was never sufficient by
// itself — the requesting user must be authenticated AND their own
// verified account email must match the order's, not just a claim.


Deno.serve(async (req) => {
  const opt = handleOptions(req);
  if (opt) return opt;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { user, error: authError } = await getRequestUser(req);
    if (!user) return jsonResponse({ error: authError || 'Not authenticated' }, 401);

    const { orderId } = (await req.json()) || {};
    if (!orderId || typeof orderId !== 'string') {
      return jsonResponse({ error: 'orderId is required' }, 400);
    }

    const admin = getAdminClient();
    const { data: order, error: fetchError } = await admin
      .from('orders')
      .select('id, user_id, shipping_address')
      .eq('id', orderId)
      .maybeSingle();

    if (fetchError) return jsonResponse({ error: fetchError.message }, 500);
    if (!order) return jsonResponse({ error: 'Order not found' }, 404);

    // Already claimed — either by this same account (nothing to do) or
    // by someone else (never silently reassign).
    if (order.user_id) {
      return jsonResponse({ attached: order.user_id === user.id, alreadyAttached: true });
    }

    const orderEmail = (order.shipping_address as Record<string, string> | null)?.email?.trim().toLowerCase();
    const accountEmail = user.email?.trim().toLowerCase();
    if (!orderEmail || !accountEmail || orderEmail !== accountEmail) {
      // Deliberately generic — doesn't confirm or deny whether the
      // order exists under a different email, avoiding a secondary
      // enumeration surface on top of the one check-email-exists
      // already guards carefully.
      return jsonResponse({ error: 'This order cannot be added to your account.' }, 403);
    }

    const { error: updateError } = await admin
      .from('orders')
      .update({ user_id: user.id })
      .eq('id', orderId)
      .is('user_id', null); // re-checked at update time too, not just at the read above — closes the gap between the two

    if (updateError) return jsonResponse({ error: updateError.message }, 500);

    return jsonResponse({ attached: true, alreadyAttached: false });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
