// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  try {
    const { data, error } = await client.auth.getUser();
    if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
    return { user: data.user, error: null };
  } catch (err) {
    // auth.getUser() THROWS (rather than returning a clean error
    // object) for a token it can't parse as a real user session — the
    // anon key every guest request sends is exactly this case: it's a
    // real JWT, but a project-level API key, not a user session token,
    // so it has no `sub` (user id) claim at all. That's "invalid
    // claim: missing sub claim" specifically. Treating it the same as
    // any other failed lookup — no user, not a crash — is what makes
    // every guest-checkout code path that calls this actually work.
    return { user: null, error: err instanceof Error ? err.message : 'Not authenticated' };
  }
}

// ═══ check-payment-status/index.ts (entry point) ═══
// ── check-payment-status ──────────────────────────────────────────
// Purpose: the Razorpay Checkout modal's `ondismiss` event is
// ambiguous on mobile — it can mean a genuine cancel, but it can also
// fire when a NetBanking/OTP flow backgrounds the browser tab (common
// on mobile banking redirects) even though the payment is still being
// processed and will complete via the webhook moments later. Treating
// every dismiss as a hard failure was causing "redirected back to
// checkout" with no indication the payment actually succeeded.
//
// This function lets the frontend poll, briefly, whether the order
// was already fulfilled in the background (by verify-razorpay-payment
// or the webhook — whichever got there first) before showing a
// failure state. It never creates or verifies anything itself — it
// only reads payment_intents/payments, which have no client RLS
// access at all, so this is the only way the frontend can check.


Deno.serve(async (req) => {
  const opt = handleOptions(req);
  if (opt) return opt;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { user, error: authError } = await getRequestUser(req);
    if (!user) return jsonResponse({ error: authError || 'Not authenticated' }, 401);

    const { provider_order_id } = await req.json();
    if (!provider_order_id) return jsonResponse({ error: 'provider_order_id is required' }, 400);

    const admin = getAdminClient();

    const { data: intent } = await admin
      .from('payment_intents')
      .select('user_id, status')
      .eq('provider_order_id', provider_order_id)
      .maybeSingle();

    if (!intent) return jsonResponse({ fulfilled: false });
    // Ownership check — a caller can only poll their own order's status.
    if (intent.user_id !== user.id) return jsonResponse({ error: 'This order does not belong to your account' }, 403);

    if (intent.status !== 'consumed') return jsonResponse({ fulfilled: false });

    const { data: payment } = await admin
      .from('payments')
      .select('order_id')
      .eq('provider_order_id', provider_order_id)
      .maybeSingle();

    return jsonResponse({ fulfilled: true, orderId: payment?.order_id || null });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
