// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  const { data, error } = await client.auth.getUser();
  if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
  return { user: data.user, error: null };
}

// ═══ inlined: _shared/razorpay.ts ═══
// ── Razorpay API + signature helpers ─────────────────────────────
export const RAZORPAY_KEY_ID = Deno.env.get('RAZORPAY_KEY_ID')!;
const RAZORPAY_KEY_SECRET = Deno.env.get('RAZORPAY_KEY_SECRET')!;

const RAZORPAY_API = 'https://api.razorpay.com/v1';

function basicAuthHeader(): string {
  return 'Basic ' + btoa(`${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}`);
}

export async function createRazorpayOrder({ amount, currency, receipt, notes }: {
  amount: number; currency: string; receipt: string; notes?: Record<string, string>;
}) {
  const res = await fetch(`${RAZORPAY_API}/orders`, {
    method: 'POST',
    headers: {
      Authorization: basicAuthHeader(),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ amount, currency, receipt, notes }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error?.description || 'Razorpay order creation failed');
  return data; // { id, amount, currency, receipt, status, ... }
}

export async function fetchRazorpayPayment(paymentId: string) {
  const res = await fetch(`${RAZORPAY_API}/payments/${paymentId}`, {
    headers: { Authorization: basicAuthHeader() },
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error?.description || 'Could not fetch payment from Razorpay');
  return data;
}

// HMAC-SHA256(order_id + "|" + payment_id, key_secret) === signature
// This is Razorpay's documented client-side checkout verification —
// it MUST only ever run server-side (this file), never in the browser.
export async function verifyCheckoutSignature({
  orderId, paymentId, signature,
}: { orderId: string; paymentId: string; signature: string }): Promise<boolean> {
  const expected = await hmacSha256Hex(`${orderId}|${paymentId}`, RAZORPAY_KEY_SECRET);
  return timingSafeEqual(expected, signature);
}

// Webhook signature: HMAC-SHA256(raw request body, webhook secret)
export async function verifyWebhookSignature({
  rawBody, signature, secret,
}: { rawBody: string; signature: string; secret: string }): Promise<boolean> {
  const expected = await hmacSha256Hex(rawBody, secret);
  return timingSafeEqual(expected, signature);
}

async function hmacSha256Hex(message: string, secret: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(message));
  return Array.from(new Uint8Array(sig)).map(b => b.toString(16).padStart(2, '0')).join('');
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// ═══ create-razorpay-order/index.ts (entry point) ═══
// ── create-razorpay-order ─────────────────────────────────────────
// POST body: { items: [{ productId, qty, variant? }], shippingAddress, billingAddress?, couponCode? }
// Requires: Authorization: Bearer <user's Supabase access token>
//
// Never trusts a price, subtotal, tax, or shipping figure from the
// client — every item's price is re-looked-up from the `products`
// table, and totals are recomputed here from scratch. Returns a real
// Razorpay order id which the frontend must use to open Razorpay
// Checkout; nothing is written to `orders` yet (see payment_intents).



// TAX_RATE/FREE_SHIPPING_THRESHOLD/SHIPPING_COST are documented (and
// read from .env.example) as paise, matching Razorpay's own convention —
// but products.price is plain rupees, so they're converted to rupees once
// here, right alongside where that assumption is defined, rather than
// mixing units throughout the calculation below.
const TAX_RATE = parseFloat(Deno.env.get('TAX_RATE') || '0.18');
const FREE_SHIPPING_THRESHOLD_RUPEES = parseInt(Deno.env.get('FREE_SHIPPING_THRESHOLD') || '500000', 10) / 100;
const STANDARD_SHIPPING_RUPEES = parseInt(Deno.env.get('SHIPPING_COST') || '8900', 10) / 100;
// Matches the amounts already shown on the checkout page's delivery
// method options — previously decorative only, since shipping cost never
// actually varied by which one was selected.
const EXPRESS_SHIPPING_RUPEES = 799;
const NEXT_DAY_SHIPPING_RUPEES = 1299;

Deno.serve(async (req) => {
  const opt = handleOptions(req);
  if (opt) return opt;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { user, error: authError } = await getRequestUser(req);
    if (!user) return jsonResponse({ error: authError || 'Not authenticated' }, 401);

    const body = await req.json();
    const { items, shippingAddress, billingAddress, couponCode } = body || {};

    if (!Array.isArray(items) || items.length === 0) {
      return jsonResponse({ error: 'No items provided' }, 400);
    }
    if (!shippingAddress || !shippingAddress.address1 || !shippingAddress.city) {
      return jsonResponse({ error: 'A valid shipping address is required' }, 400);
    }

    const admin = getAdminClient();

    // Re-price every line item from the database — the client's price,
    // if it sent one at all, is ignored completely.
    const pricedItems = [];
    for (const raw of items) {
      const slugOrId = raw.productId;
      const qty = Math.max(1, parseInt(raw.qty, 10) || 1);
      if (!slugOrId) return jsonResponse({ error: 'Each item needs a productId' }, 400);

      // Look up by slug — every cart item's productId from the frontend
      // is a slug, never a raw UUID (see the app-wide convention in
      // src/utils/normalizeProduct.js). `id` is a UUID column, so a
      // combined `.or('id.eq.X,slug.eq.X')` filter here would throw a
      // Postgres "invalid input syntax for type uuid" error the instant
      // X isn't UUID-shaped — which is always, since slugs never are.
      // This is the exact same bug that was fixed in fetchProductById()
      // on the frontend; fixed the same way here: query by slug alone,
      // and only attempt an id-based lookup if the string actually
      // looks like a UUID.
      const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(slugOrId);
      let product = null, productError = null;
      const selectClause = 'id, slug, name, price, stock, is_active, product_images(url, is_primary, sort_order)';

      const bySlug = await admin.from('products').select(selectClause).eq('slug', slugOrId).maybeSingle();
      if (bySlug.error) productError = bySlug.error;
      else if (bySlug.data) product = bySlug.data;
      else if (isUuid) {
        const byId = await admin.from('products').select(selectClause).eq('id', slugOrId).maybeSingle();
        if (byId.error) productError = byId.error;
        else product = byId.data;
      }

      if (productError || !product) {
        return jsonResponse({ error: `Product not found: ${slugOrId}` }, 400);
      }
      if (!product.is_active) {
        return jsonResponse({ error: `"${product.name}" is no longer available` }, 400);
      }

      // Variant-aware stock check (e.g. a specific shoe size) — takes
      // over from the parent product's own stock entirely when a
      // variantId is given, since that's the real, tracked figure for
      // that option. The variantId is never trusted blindly: it must
      // actually belong to this product, or a client could otherwise
      // claim a cheap/in-stock variant from a different product.
      let variantId: string | null = null;
      let variantPriceAdj = 0;
      let variantSnapshot: Record<string, string> = {};

      if (raw.variantId) {
        const { data: variant, error: variantError } = await admin
          .from('product_variants')
          .select('id, product_id, name, value, stock, is_active, price_adj')
          .eq('id', raw.variantId)
          .maybeSingle();

        if (variantError || !variant) {
          return jsonResponse({ error: `Selected option not found for "${product.name}"` }, 400);
        }
        if (variant.product_id !== product.id) {
          return jsonResponse({ error: `Selected option does not belong to "${product.name}"` }, 400);
        }
        if (!variant.is_active) {
          return jsonResponse({ error: `"${product.name}" (${variant.value}) is no longer available` }, 400);
        }
        if (variant.stock < qty) {
          return jsonResponse({ error: `Only ${variant.stock} of "${product.name}" (${variant.value}) left in stock` }, 400);
        }
        variantId = variant.id;
        variantPriceAdj = variant.price_adj || 0;
        variantSnapshot = { [variant.name]: variant.value };
      } else if (product.stock < qty) {
        return jsonResponse({ error: `Only ${product.stock} of "${product.name}" left in stock` }, 400);
      }

      const primaryImage = (product.product_images || [])
        .sort((a: any, b: any) => (b.is_primary ? 1 : 0) - (a.is_primary ? 1 : 0))[0]?.url || null;

      pricedItems.push({
        product_id: product.id,
        slug: product.slug,
        name: product.name,
        price: product.price + variantPriceAdj, // server price (+ variant adjustment, e.g. a size-specific upcharge), never the client's
        qty,
        variant: Object.keys(variantSnapshot).length ? variantSnapshot : (raw.variant || {}),
        variant_id: variantId,
        image_url: primaryImage,
      });
    }

    const subtotalRupees = pricedItems.reduce((sum, i) => sum + i.price * i.qty, 0);
    const taxRupees = Math.round(subtotalRupees * TAX_RATE);

    // Shipping now actually reflects which delivery method was selected —
    // previously this only ever checked the free-shipping threshold and
    // ignored the choice entirely, so Express/Next Day never cost anything
    // extra despite what the checkout UI displayed.
    const deliveryMethod = shippingAddress?.delivery || 'std';
    let shippingCostRupees;
    if (deliveryMethod === 'exp') shippingCostRupees = EXPRESS_SHIPPING_RUPEES;
    else if (deliveryMethod === 'nxt') shippingCostRupees = NEXT_DAY_SHIPPING_RUPEES;
    else shippingCostRupees = subtotalRupees >= FREE_SHIPPING_THRESHOLD_RUPEES ? 0 : STANDARD_SHIPPING_RUPEES;

    const discountRupees = 0; // coupon logic can compute a real value here later; structure is already in place
    const totalRupees = subtotalRupees + taxRupees + shippingCostRupees - discountRupees;

    // products.price (and therefore every figure above) is stored in plain
    // rupees — matching the convention used everywhere else in this app
    // (cart, product pages, admin product list). But orders.total,
    // orders.subtotal/tax/shipping_cost, and payments.amount are all read
    // elsewhere (admin Orders page, order confirmation page, account page)
    // by dividing by 100 — i.e. those columns are meant to hold paise, the
    // same unit Razorpay's own API requires. This was the actual bug: this
    // function was computing everything in rupees and hoping downstream
    // dividers treated it as paise, so a real order total of ₹39,578 was
    // charged as ₹395.78 (39578 paise). Converting once, right here, to
    // paise for every aggregate figure — but NOT for the per-item `price`
    // above, which order_items.price already displays without dividing —
    // fixes it at the one place all three (Razorpay, DB storage, and
    // display) actually agree on.
    const subtotal = Math.round(subtotalRupees * 100);
    const tax = Math.round(taxRupees * 100);
    const shippingCost = Math.round(shippingCostRupees * 100);
    const discount = Math.round(discountRupees * 100);
    const total = Math.round(totalRupees * 100);

    if (total <= 0) return jsonResponse({ error: 'Order total must be greater than zero' }, 400);

    // Razorpay order amount/currency are what the customer will actually
    // be charged — this is the number that matters, computed above.
    const receipt = `ri_${Date.now()}_${user.id.slice(0, 8)}`;
    const razorpayOrder = await createRazorpayOrder({
      amount: total,
      currency: 'INR',
      receipt,
      notes: { user_id: user.id },
    });

    const { error: intentError } = await admin.from('payment_intents').insert([{
      user_id: user.id,
      provider: 'razorpay',
      provider_order_id: razorpayOrder.id,
      items: pricedItems,
      shipping_address: shippingAddress,
      billing_address: billingAddress || shippingAddress,
      coupon_code: couponCode || null,
      subtotal, tax, shipping_cost: shippingCost, discount, total,
      status: 'created',
    }]);

    if (intentError) return jsonResponse({ error: intentError.message }, 500);

    return jsonResponse({
      order_id: razorpayOrder.id,
      amount: total,
      currency: 'INR',
      key_id: RAZORPAY_KEY_ID, // public key, safe to return to the client
    });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
