// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  const { data, error } = await client.auth.getUser();
  if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
  return { user: data.user, error: null };
}

// ═══ fetch-order/index.ts (entry point) ═══
// ── fetch-order ────────────────────────────────────────────────────
// Resolves a single order for display, for BOTH registered and guest
// customers, through one consistent path — rather than relying on the
// client's direct RLS-gated query, which works fine for a logged-in
// owner but can never work for a guest: orders_own's policy is
// `user_id = auth.uid()`, and a guest has no auth.uid() at all
// (it's NULL, and NULL = NULL is not true in Postgres) — so a guest
// would see a blank/failed confirmation page immediately after paying,
// every single time, with no way to fix it from the client side alone.
//
// POST body: { orderId: string }
// Authorization header is optional — sent automatically by the
// Supabase client if the visitor happens to be logged in, absent for
// a genuine guest.
//
// Authorization model:
//   - Logged in, and this order's user_id matches: allowed.
//   - Not logged in, and this order has NO user_id (a real guest
//     order): allowed. The order id itself is a v4 UUID — 122 bits of
//     randomness, not realistically guessable — so knowing it (from
//     the post-checkout redirect, which is the only place it's ever
//     handed out) is treated as sufficient proof of ownership, the
//     same "capability URL" pattern Stripe/Shopify use for their own
//     guest confirmation pages.
//   - Anything else (wrong owner, or a guest trying to view a
//     registered order): a generic not-found, never a distinguishing
//     "wrong owner" vs "doesn't exist" response.


Deno.serve(async (req) => {
  const opt = handleOptions(req);
  if (opt) return opt;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { orderId } = (await req.json()) || {};
    if (!orderId || typeof orderId !== 'string') {
      return jsonResponse({ error: 'orderId is required' }, 400);
    }

    const { user } = await getRequestUser(req); // null for a guest — not an error case here
    const admin = getAdminClient();

    const { data: order, error } = await admin
      .from('orders')
      .select(`*, order_items(*, product:product_id(name, slug, brand, category_slug, product_images(url, is_primary))), payments(*), shipments(*)`)
      .eq('id', orderId)
      .maybeSingle();

    if (error) return jsonResponse({ error: error.message }, 500);

    const authorized = order && (
      (user && order.user_id === user.id) ||
      (!user && order.user_id === null)
    );

    // Same response either way — an order that exists but isn't yours
    // shouldn't be distinguishable from one that doesn't exist at all.
    if (!authorized) return jsonResponse({ data: null, error: null });

    return jsonResponse({ data: order, error: null });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
