// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────


// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/email.ts ═══
// ── Order confirmation email (Resend) ─────────────────────────────
// Sends from Resend's own verified default sender (onboarding@resend.dev)
// with Reply-To set to your real support inbox — a third-party service
// can never send authenticated mail claiming to be @gmail.com (SPF/DKIM/
// DMARC would reject it), so this is the correct approach until a real
// domain is verified with Resend, at which point only FROM_EMAIL below
// needs to change.
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
const FROM_EMAIL = Deno.env.get('ORDER_EMAIL_FROM') || 'RacquetIn <onboarding@resend.dev>';
const REPLY_TO_EMAIL = Deno.env.get('ORDER_EMAIL_REPLY_TO') || 'racquetinsports@gmail.com';

function formatRupees(paise: number): string {
  return '₹' + Math.round(paise / 100).toLocaleString('en-IN');
}

export async function sendOrderConfirmationEmail({
  toEmail, toName, order, items,
}: {
  toEmail: string;
  toName?: string | null;
  order: { order_number: string; total: number; payment_method?: string | null; created_at: string };
  items: Array<{ name: string; price: number; qty: number }>;
}): Promise<{ sent: boolean; error?: string }> {
  // Email is a nice-to-have, never allowed to block or fail order
  // fulfillment — callers should treat a failure here as non-fatal.
  if (!RESEND_API_KEY) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const itemRows = items.map(i => `
    <tr>
      <td style="padding:10px 0;border-bottom:1px solid #eee;">${escapeHtml(i.name)} × ${i.qty}</td>
      <td style="padding:10px 0;border-bottom:1px solid #eee;text-align:right;">${formatRupees(i.price * i.qty)}</td>
    </tr>`).join('');

  const html = `
  <div style="font-family:Arial,sans-serif;max-width:520px;margin:0 auto;color:#111;">
    <h1 style="font-size:20px;letter-spacing:-0.02em;">RacquetIn</h1>
    <p style="font-size:15px;">Hi ${toName ? escapeHtml(toName) : 'there'},</p>
    <p style="font-size:15px;">Thanks for your order — here's your confirmation.</p>
    <table style="width:100%;border-collapse:collapse;margin:20px 0;font-size:14px;">
      <tr><td style="padding:6px 0;color:#666;">Order Number</td><td style="padding:6px 0;text-align:right;font-weight:600;">${escapeHtml(order.order_number)}</td></tr>
      <tr><td style="padding:6px 0;color:#666;">Order Date</td><td style="padding:6px 0;text-align:right;">${new Date(order.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</td></tr>
      ${order.payment_method ? `<tr><td style="padding:6px 0;color:#666;">Payment Method</td><td style="padding:6px 0;text-align:right;text-transform:capitalize;">${escapeHtml(order.payment_method)}</td></tr>` : ''}
    </table>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      ${itemRows}
      <tr><td style="padding:14px 0 0;font-weight:700;">Total Paid</td><td style="padding:14px 0 0;text-align:right;font-weight:700;">${formatRupees(order.total)}</td></tr>
    </table>
    <p style="font-size:13px;color:#666;margin-top:32px;">We'll send another email once your order ships. Questions? Just reply to this email.</p>
  </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: toEmail,
        reply_to: REPLY_TO_EMAIL,
        subject: `Order Confirmed — ${order.order_number}`,
        html,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      return { sent: false, error: `Resend API error (${res.status}): ${body}` };
    }
    return { sent: true };
  } catch (err) {
    return { sent: false, error: err instanceof Error ? err.message : 'Unknown email error' };
  }
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));
}

// ── Email-verified welcome email ──────────────────────────────────
// Sent exactly once, server-side, the moment a user's email_confirmed_at
// transitions from null to a real timestamp — see
// supabase/migration_email_verification_webhook.sql for the trigger
// that calls the on-email-verified function, which calls this. Not
// triggered from the client, so it fires reliably even if the person
// closes the tab right after clicking the verification link.
export async function sendVerificationWelcomeEmail({
  toEmail, toName,
}: {
  toEmail: string;
  toName?: string | null;
}): Promise<{ sent: boolean; error?: string }> {
  if (!RESEND_API_KEY) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const html = `
  <div style="font-family:Arial,sans-serif;max-width:520px;margin:0 auto;color:#111;">
    <h1 style="font-size:20px;letter-spacing:-0.02em;">RacquetIn</h1>
    <p style="font-size:15px;">Hi ${toName ? escapeHtml(toName) : 'there'},</p>
    <p style="font-size:15px;">Your email is verified and your account is ready to go.</p>
    <p style="font-size:15px;">Browse the collection, track orders, and manage your wishlist — all from your account.</p>
    <p style="font-size:13px;color:#666;margin-top:32px;">Questions? Just reply to this email.</p>
  </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: toEmail,
        reply_to: REPLY_TO_EMAIL,
        subject: 'Welcome to RacquetIn — you\'re verified',
        html,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      return { sent: false, error: `Resend API error (${res.status}): ${body}` };
    }
    return { sent: true };
  } catch (err) {
    return { sent: false, error: err instanceof Error ? err.message : 'Unknown email error' };
  }
}

// ═══ on-email-verified/index.ts (entry point) ═══
// ── on-email-verified ────────────────────────────────────────────
// Called by a Postgres trigger on auth.users (see
// supabase/migration_email_verification_webhook.sql) — NOT called
// from the frontend. Fires exactly once, server-side, the moment a
// user's email_confirmed_at transitions from null to a real
// timestamp, so the welcome email goes out reliably even if the
// person closes the tab immediately after clicking the verification
// link.
//
// Auth: this endpoint has no user JWT to check (Postgres is calling
// it, not a logged-in browser), so it's gated by a shared secret
// header instead — set EMAIL_WEBHOOK_SECRET as an Edge Function
// secret and pass the same value as the trigger's x-webhook-secret
// header. Reject anything that doesn't match, so the URL alone (which
// is not secret — it's visible in the trigger definition to anyone
// with database access, and technically guessable) can't be used to
// spam arbitrary email addresses.


const EMAIL_WEBHOOK_SECRET = Deno.env.get('EMAIL_WEBHOOK_SECRET');

Deno.serve(async (req) => {
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    if (!EMAIL_WEBHOOK_SECRET) {
      // Fail closed, not open — an unconfigured secret must never be
      // treated as "no auth required".
      return jsonResponse({ error: 'EMAIL_WEBHOOK_SECRET not configured' }, 500);
    }
    if (req.headers.get('x-webhook-secret') !== EMAIL_WEBHOOK_SECRET) {
      return jsonResponse({ error: 'Unauthorized' }, 401);
    }

    const body = await req.json();
    const record = body?.record;
    const oldRecord = body?.old_record;

    // Defense in depth: the SQL trigger's WHEN clause already only
    // fires on a genuine null → non-null transition, but re-checking
    // here means this function is safe even if called directly or
    // retried by Postgres with a stale payload.
    const justVerified = !oldRecord?.email_confirmed_at && !!record?.email_confirmed_at;
    if (!justVerified) {
      return jsonResponse({ skipped: true, reason: 'Not a verification transition' });
    }

    const email = record?.email;
    if (!email) return jsonResponse({ error: 'Missing email on user record' }, 400);

    const fullName = record?.raw_user_meta_data?.full_name || null;

    // Best-effort — a failed send here should never make the
    // underlying auth.users update (or the trigger that called this)
    // look like it failed. Delivery status is visible in the Resend
    // dashboard if you need to check it.
    const result = await sendVerificationWelcomeEmail({ toEmail: email, toName: fullName });

    return jsonResponse({ success: true, emailSent: result.sent, emailError: result.error || null });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
