// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  try {
    const { data, error } = await client.auth.getUser();
    if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
    return { user: data.user, error: null };
  } catch (err) {
    // auth.getUser() THROWS (rather than returning a clean error
    // object) for a token it can't parse as a real user session — the
    // anon key every guest request sends is exactly this case: it's a
    // real JWT, but a project-level API key, not a user session token,
    // so it has no `sub` (user id) claim at all. That's "invalid
    // claim: missing sub claim" specifically. Treating it the same as
    // any other failed lookup — no user, not a crash — is what makes
    // every guest-checkout code path that calls this actually work.
    return { user: null, error: err instanceof Error ? err.message : 'Not authenticated' };
  }
}

// ═══ shiprocket-shipment/index.ts (entry point) ═══
// ── Shiprocket shipment actions ──────────────────────────────────
// Called by the admin dashboard (via src/lib/shipping/shiprocketProvider.js)
// when an admin creates or cancels a shipment with Shiprocket selected
// as the provider. Holds the actual Shiprocket account credentials —
// the frontend never sees them, same pattern as Razorpay.
//
// Required Edge Function secrets (Project Settings → Edge Functions → Secrets):
//   SHIPROCKET_EMAIL             — the API user's email (Settings → API →
//                                   Add New API User in the Shiprocket
//                                   dashboard; NOT your main login email)
//   SHIPROCKET_PASSWORD          — sent to your registered email when
//                                   you create that API user
//   SHIPROCKET_PICKUP_LOCATION   — the pickup address's "nickname" as
//                                   configured in Shiprocket's Settings →
//                                   Pickup Addresses (not the full address)
//   SHIPROCKET_PICKUP_PINCODE    — that same pickup address's PIN code
//                                   (used for the courier serviceability
//                                   check, which needs a pincode, not a name)


const SHIPROCKET_EMAIL = Deno.env.get('SHIPROCKET_EMAIL');
const SHIPROCKET_PASSWORD = Deno.env.get('SHIPROCKET_PASSWORD');
const SHIPROCKET_PICKUP_LOCATION = Deno.env.get('SHIPROCKET_PICKUP_LOCATION');
// Distinct from SHIPROCKET_PICKUP_LOCATION on purpose: that's the
// pickup address's *nickname* (what order creation expects), this is
// its actual PIN code (what the serviceability check expects) — both
// come from the same Settings → Pickup Addresses entry in Shiprocket,
// just different fields of it.
const SHIPROCKET_PICKUP_PINCODE = Deno.env.get('SHIPROCKET_PICKUP_PINCODE');
const SHIPROCKET_BASE = 'https://apiv2.shiprocket.in/v1/external';

// Shiprocket's own auth token is valid 240 hours (10 days). Cached at
// module scope so it survives across warm invocations of the same
// function instance — cold starts just re-authenticate, which is fine,
// login is cheap and infrequent either way.
let cachedToken: { token: string; expiresAt: number } | null = null;

async function getShiprocketToken(): Promise<string> {
  if (cachedToken && cachedToken.expiresAt > Date.now()) return cachedToken.token;
  if (!SHIPROCKET_EMAIL || !SHIPROCKET_PASSWORD) {
    throw new Error('SHIPROCKET_EMAIL / SHIPROCKET_PASSWORD not configured as Edge Function secrets');
  }
  const res = await fetch(`${SHIPROCKET_BASE}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: SHIPROCKET_EMAIL, password: SHIPROCKET_PASSWORD }),
  });
  const body = await res.json().catch(() => null);
  if (!res.ok || !body?.token) {
    throw new Error(`Shiprocket auth failed (${res.status}): ${JSON.stringify(body)}`);
  }
  // Refresh at 200h rather than waiting for the full 240h — leaves a
  // safety margin instead of racing an exact expiry.
  cachedToken = { token: body.token, expiresAt: Date.now() + 1000 * 60 * 60 * 200 };
  return cachedToken.token;
}

async function shiprocketFetch(path: string, options: RequestInit = {}) {
  const token = await getShiprocketToken();
  const res = await fetch(`${SHIPROCKET_BASE}${path}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
      ...options.headers,
    },
  });
  const body = await res.json().catch(() => null);
  if (!res.ok) {
    throw new Error(`Shiprocket API error (${res.status}) at ${path}: ${JSON.stringify(body)}`);
  }
  return body;
}

// Best-effort: picks the cheapest serviceable courier for this
// pickup→delivery pair and assigns it, producing a real AWB/tracking
// number in the same step as order creation. This part of Shiprocket's
// API has more field-name variance across accounts/couriers than the
// well-documented auth/create-order/cancel-order calls above, so it's
// deliberately isolated in its own try/catch — if it fails for any
// reason, the Shiprocket order itself still exists and can be
// completed manually from the Shiprocket dashboard rather than the
// whole shipment creation failing.
async function autoAssignCourier(shiprocketOrderId: number, shipmentId: number, pickupPincode: string, deliveryPincode: string, weight: number, isCod: boolean) {
  const serviceability = await shiprocketFetch(
    `/courier/serviceability/?pickup_postcode=${encodeURIComponent(pickupPincode)}&delivery_postcode=${encodeURIComponent(deliveryPincode)}&weight=${weight}&cod=${isCod ? 1 : 0}`
  );
  const options = serviceability?.data?.available_courier_companies || [];
  if (!options.length) throw new Error('No serviceable couriers returned for this route');

  const recommendedId = serviceability?.data?.recommended_courier_company_id;
  const chosen = options.find((c: any) => c.courier_company_id === recommendedId)
    || [...options].sort((a: any, b: any) => (a.rate ?? Infinity) - (b.rate ?? Infinity))[0];

  const assigned = await shiprocketFetch('/courier/assign/awb', {
    method: 'POST',
    body: JSON.stringify({ shipment_id: shipmentId, courier_id: chosen.courier_company_id }),
  });

  const awb = assigned?.response?.data?.awb_code;
  if (!awb) throw new Error(`AWB assignment returned no awb_code: ${JSON.stringify(assigned)}`);

  return {
    trackingNumber: awb,
    trackingUrl: `https://shiprocket.co/tracking/${awb}`,
    courierName: assigned?.response?.data?.courier_name || chosen.courier_name,
  };
}

Deno.serve(async (req) => {
  const preflight = handleOptions(req);
  if (preflight) return preflight;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { user, error: authError } = await getRequestUser(req);
    if (!user) return jsonResponse({ error: authError || 'Not authenticated' }, 401);

    const admin = getAdminClient();
    const { data: adminRow } = await admin.from('admin_users').select('user_id').eq('user_id', user.id).maybeSingle();
    if (!adminRow) return jsonResponse({ error: 'Admin access required' }, 403);

    const { action, order, shipment } = await req.json();

    if (action === 'create') {
      if (!SHIPROCKET_PICKUP_LOCATION) {
        throw new Error('SHIPROCKET_PICKUP_LOCATION not configured as an Edge Function secret');
      }
      const addr = order?.shipping_address || {};
      if (addr.country && addr.country !== 'India') {
        // Checkout is now India-only (see OtherPages.jsx CheckoutPage),
        // but this guards any order placed before that fix — Shiprocket's
        // order-creation API used here is domestic-only, so attempting
        // it would just fail with a confusing generic validation error.
        throw new Error(`Cannot create a Shiprocket shipment for a non-India order (country: ${addr.country}). Ship this one manually.`);
      }
      const items = (order?.order_items || []).map((i: any) => ({
        name: i.name,
        sku: i.product_id || i.id,
        units: i.qty,
        selling_price: (i.price || 0) / 100, // order_items.price is stored in paise
      }));
      if (!items.length) throw new Error('Order has no items to ship');

      const payload = {
        order_id: order.order_number,
        order_date: (order.created_at || new Date().toISOString()).slice(0, 19).replace('T', ' '),
        pickup_location: SHIPROCKET_PICKUP_LOCATION,
        billing_customer_name: addr.firstName || addr.first_name || '',
        billing_last_name: addr.lastName || addr.last_name || '',
        billing_address: addr.address1 || addr.address_1 || '',
        billing_address_2: addr.address2 || addr.address_2 || '',
        billing_city: addr.city || '',
        billing_pincode: addr.postcode || addr.pincode || '',
        billing_state: addr.state || '',
        billing_country: addr.country || 'India',
        billing_email: addr.email || '',
        billing_phone: addr.phone || '',
        shipping_is_billing: true,
        order_items: items,
        payment_method: order.payment_method === 'cod' ? 'COD' : 'Prepaid',
        sub_total: (order.subtotal || 0) / 100,
        // Placeholder package dimensions/weight — RacquetIn doesn't
        // currently store per-product shipping dimensions, so these
        // are a single reasonable default for a small parcel rather
        // than a real per-order calculation. Revisit once product
        // dimensions exist (see final report).
        length: 30, breadth: 20, height: 10, weight: 1,
      };

      const created = await shiprocketFetch('/orders/create/adhoc', {
        method: 'POST',
        body: JSON.stringify(payload),
      });

      let tracking: { trackingNumber?: string; trackingUrl?: string; courierName?: string } = {};
      let courierAssignError: string | null = null;
      if (!SHIPROCKET_PICKUP_PINCODE) {
        courierAssignError = 'SHIPROCKET_PICKUP_PINCODE not configured — order created, but courier must be assigned manually in the Shiprocket dashboard';
      } else {
        try {
          tracking = await autoAssignCourier(
            created.order_id,
            created.shipment_id,
            SHIPROCKET_PICKUP_PINCODE,
            addr.postcode || addr.pincode || '',
            payload.weight,
            order.payment_method === 'cod'
          );
        } catch (err) {
          courierAssignError = err instanceof Error ? err.message : 'Courier auto-assignment failed';
        }
      }

      return jsonResponse({
        trackingNumber: tracking.trackingNumber,
        trackingUrl: tracking.trackingUrl,
        courierName: tracking.courierName,
        shiprocketOrderId: created.order_id,
        shiprocketShipmentId: created.shipment_id,
        courierAssignError, // non-null means: order created fine, but finish courier assignment manually in Shiprocket's dashboard
        raw: created,
      });
    }

    if (action === 'cancel') {
      if (!shipment?.provider_order_id) throw new Error('Missing Shiprocket order id to cancel');
      const result = await shiprocketFetch('/orders/cancel', {
        method: 'POST',
        body: JSON.stringify({ ids: [shipment.provider_order_id] }),
      });
      return jsonResponse({ cancelled: true, raw: result });
    }

    return jsonResponse({ error: `Unknown action: ${action}` }, 400);
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
