// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  try {
    const { data, error } = await client.auth.getUser();
    if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
    return { user: data.user, error: null };
  } catch (err) {
    // auth.getUser() THROWS (rather than returning a clean error
    // object) for a token it can't parse as a real user session — the
    // anon key every guest request sends is exactly this case: it's a
    // real JWT, but a project-level API key, not a user session token,
    // so it has no `sub` (user id) claim at all. That's "invalid
    // claim: missing sub claim" specifically. Treating it the same as
    // any other failed lookup — no user, not a crash — is what makes
    // every guest-checkout code path that calls this actually work.
    return { user: null, error: err instanceof Error ? err.message : 'Not authenticated' };
  }
}

// ═══ shiprocket-webhook/index.ts (entry point) ═══
// ── Shiprocket webhook ────────────────────────────────────────────
// Receives Shiprocket's push notifications for tracking updates —
// set this function's URL in Shiprocket's dashboard under
// Settings → API → Webhooks, with the same value as
// SHIPROCKET_WEBHOOK_SECRET set below as the "security token" (sent
// back to us as an x-api-key header on every call, per Shiprocket's
// own webhook docs).
//
// This is what keeps shipment_status current automatically once an
// order ships — without it, tracking would only ever update when an
// admin manually clicks "Mark Shipped"/"Mark Delivered" in the
// dashboard, same as the 'manual' provider.


const SHIPROCKET_WEBHOOK_SECRET = Deno.env.get('SHIPROCKET_WEBHOOK_SECRET');

// Best-effort mapping from Shiprocket's status vocabulary to this
// app's shipment_status enum (pending | packed | shipped | in_transit
// | delivered | cancelled | returned). Shiprocket's own status list is
// larger and not exhaustively documented here — an unmapped status is
// deliberately left alone (event still logged, shipment_status
// untouched) rather than guessed at.
const STATUS_MAP: Record<string, string> = {
  'NEW': 'pending',
  'MANIFEST GENERATED': 'packed',
  'PICKED UP': 'shipped',
  'SHIPPED': 'shipped',
  'IN TRANSIT': 'in_transit',
  'OUT FOR DELIVERY': 'in_transit',
  'DELIVERED': 'delivered',
  'CANCELLED': 'cancelled',
  'CANCELED': 'cancelled',
  'RTO INITIATED': 'returned',
  'RTO DELIVERED': 'returned',
  'RETURNED': 'returned',
};

Deno.serve(async (req) => {
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    if (SHIPROCKET_WEBHOOK_SECRET && req.headers.get('x-api-key') !== SHIPROCKET_WEBHOOK_SECRET) {
      return jsonResponse({ error: 'Unauthorized' }, 401);
    }

    const body = await req.json();
    const awb = body?.awb;
    const currentStatus = (body?.current_status || body?.shipment_status || '').toUpperCase();
    if (!awb) return jsonResponse({ skipped: true, reason: 'No awb in payload' });

    const admin = getAdminClient();
    const { data: shipment } = await admin
      .from('shipments')
      .select('*')
      .eq('tracking_number', awb)
      .maybeSingle();

    if (!shipment) {
      // Not necessarily an error — could be a webhook for an order
      // this project didn't create (unlikely but not impossible on a
      // shared Shiprocket account). Acknowledge so Shiprocket doesn't
      // keep retrying, but don't pretend anything was updated.
      return jsonResponse({ skipped: true, reason: 'No shipment found for this awb' });
    }

    const mappedStatus = STATUS_MAP[currentStatus];
    if (mappedStatus && mappedStatus !== shipment.shipment_status) {
      await admin.from('shipments').update({ shipment_status: mappedStatus }).eq('id', shipment.id);
    }

    // Avoid spamming an identical consecutive event on repeated
    // webhook calls for the same status (Shiprocket can call this
    // more than once per real status change).
    const { data: lastEvent } = await admin
      .from('shipment_events')
      .select('event_type, description')
      .eq('shipment_id', shipment.id)
      .order('occurred_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    const eventType = mappedStatus || 'note';
    const description = body?.current_status || body?.shipment_status || 'Tracking update';
    if (!lastEvent || lastEvent.event_type !== eventType || lastEvent.description !== description) {
      await admin.from('shipment_events').insert([{
        shipment_id: shipment.id,
        event_type: eventType,
        description,
        location: body?.scans?.[body.scans.length - 1]?.location || null,
      }]);
    }

    return jsonResponse({ success: true, mappedStatus: mappedStatus || null });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
