// ─────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/flatten-functions.mjs — do not hand-edit.
// Regenerate with: node scripts/flatten-functions.mjs
// Paste this whole file into the Supabase Dashboard function editor.
// ─────────────────────────────────────────────────────────────
import { SupabaseClient, createClient } from 'jsr:@supabase/supabase-js@2';

// ═══ inlined: _shared/cors.ts ═══
// ── CORS ──────────────────────────────────────────────────────────
// Shared across all three Edge Functions. Razorpay's webhook doesn't
// need CORS (server-to-server), but it's harmless to include.
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export function handleOptions(req: Request): Response | null {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }
  return null;
}

export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// ═══ inlined: _shared/supabaseClients.ts ═══
// ── Supabase clients for Edge Functions ──────────────────────────
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatically
// injected by the Supabase platform into every Edge Function's
// runtime environment — you do not need to set these yourself via
// `supabase secrets set` (doing so is harmless but redundant).

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Full-privilege client — bypasses RLS entirely. Only ever used
// server-side, never returned or exposed to the caller.
export function getAdminClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
}

// Resolves the calling user from the request's own JWT (the
// anon-key client the frontend already authenticated with) — this is
// how each Edge Function knows *who* is checking out without ever
// trusting a user id the client could have sent in the request body.
export async function getRequestUser(req: Request) {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return { user: null, error: 'Missing Authorization header' };

  const client = createClient(SUPABASE_URL, Deno.env.get('SUPABASE_ANON_KEY')!, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });
  const { data, error } = await client.auth.getUser();
  if (error || !data?.user) return { user: null, error: error?.message || 'Not authenticated' };
  return { user: data.user, error: null };
}

// ═══ inlined: _shared/razorpay.ts ═══
// ── Razorpay API + signature helpers ─────────────────────────────
export const RAZORPAY_KEY_ID = Deno.env.get('RAZORPAY_KEY_ID')!;
const RAZORPAY_KEY_SECRET = Deno.env.get('RAZORPAY_KEY_SECRET')!;

const RAZORPAY_API = 'https://api.razorpay.com/v1';

function basicAuthHeader(): string {
  return 'Basic ' + btoa(`${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}`);
}

export async function createRazorpayOrder({ amount, currency, receipt, notes }: {
  amount: number; currency: string; receipt: string; notes?: Record<string, string>;
}) {
  const res = await fetch(`${RAZORPAY_API}/orders`, {
    method: 'POST',
    headers: {
      Authorization: basicAuthHeader(),
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ amount, currency, receipt, notes }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error?.description || 'Razorpay order creation failed');
  return data; // { id, amount, currency, receipt, status, ... }
}

export async function fetchRazorpayPayment(paymentId: string) {
  const res = await fetch(`${RAZORPAY_API}/payments/${paymentId}`, {
    headers: { Authorization: basicAuthHeader() },
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error?.description || 'Could not fetch payment from Razorpay');
  return data;
}

// HMAC-SHA256(order_id + "|" + payment_id, key_secret) === signature
// This is Razorpay's documented client-side checkout verification —
// it MUST only ever run server-side (this file), never in the browser.
export async function verifyCheckoutSignature({
  orderId, paymentId, signature,
}: { orderId: string; paymentId: string; signature: string }): Promise<boolean> {
  const expected = await hmacSha256Hex(`${orderId}|${paymentId}`, RAZORPAY_KEY_SECRET);
  return timingSafeEqual(expected, signature);
}

// Webhook signature: HMAC-SHA256(raw request body, webhook secret)
export async function verifyWebhookSignature({
  rawBody, signature, secret,
}: { rawBody: string; signature: string; secret: string }): Promise<boolean> {
  const expected = await hmacSha256Hex(rawBody, secret);
  return timingSafeEqual(expected, signature);
}

async function hmacSha256Hex(message: string, secret: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(message));
  return Array.from(new Uint8Array(sig)).map(b => b.toString(16).padStart(2, '0')).join('');
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// ═══ inlined: _shared/email.ts ═══
// ── Order confirmation email (Resend) ─────────────────────────────
// Sends from Resend's own verified default sender (onboarding@resend.dev)
// with Reply-To set to your real support inbox — a third-party service
// can never send authenticated mail claiming to be @gmail.com (SPF/DKIM/
// DMARC would reject it), so this is the correct approach until a real
// domain is verified with Resend, at which point only FROM_EMAIL below
// needs to change.
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
const FROM_EMAIL = Deno.env.get('ORDER_EMAIL_FROM') || 'RacquetIn <onboarding@resend.dev>';
const REPLY_TO_EMAIL = Deno.env.get('ORDER_EMAIL_REPLY_TO') || 'racquetinsports@gmail.com';

function formatRupees(paise: number): string {
  return '₹' + Math.round(paise / 100).toLocaleString('en-IN');
}

export async function sendOrderConfirmationEmail({
  toEmail, toName, order, items,
}: {
  toEmail: string;
  toName?: string | null;
  order: { order_number: string; total: number; payment_method?: string | null; created_at: string };
  items: Array<{ name: string; price: number; qty: number }>;
}): Promise<{ sent: boolean; error?: string }> {
  // Email is a nice-to-have, never allowed to block or fail order
  // fulfillment — callers should treat a failure here as non-fatal.
  if (!RESEND_API_KEY) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const itemRows = items.map(i => `
    <tr>
      <td style="padding:10px 0;border-bottom:1px solid #eee;">${escapeHtml(i.name)} × ${i.qty}</td>
      <td style="padding:10px 0;border-bottom:1px solid #eee;text-align:right;">${formatRupees(i.price * i.qty)}</td>
    </tr>`).join('');

  const html = `
  <div style="font-family:Arial,sans-serif;max-width:520px;margin:0 auto;color:#111;">
    <h1 style="font-size:20px;letter-spacing:-0.02em;">RacquetIn</h1>
    <p style="font-size:15px;">Hi ${toName ? escapeHtml(toName) : 'there'},</p>
    <p style="font-size:15px;">Thanks for your order — here's your confirmation.</p>
    <table style="width:100%;border-collapse:collapse;margin:20px 0;font-size:14px;">
      <tr><td style="padding:6px 0;color:#666;">Order Number</td><td style="padding:6px 0;text-align:right;font-weight:600;">${escapeHtml(order.order_number)}</td></tr>
      <tr><td style="padding:6px 0;color:#666;">Order Date</td><td style="padding:6px 0;text-align:right;">${new Date(order.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</td></tr>
      ${order.payment_method ? `<tr><td style="padding:6px 0;color:#666;">Payment Method</td><td style="padding:6px 0;text-align:right;text-transform:capitalize;">${escapeHtml(order.payment_method)}</td></tr>` : ''}
    </table>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      ${itemRows}
      <tr><td style="padding:14px 0 0;font-weight:700;">Total Paid</td><td style="padding:14px 0 0;text-align:right;font-weight:700;">${formatRupees(order.total)}</td></tr>
    </table>
    <p style="font-size:13px;color:#666;margin-top:32px;">We'll send another email once your order ships. Questions? Just reply to this email.</p>
  </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: toEmail,
        reply_to: REPLY_TO_EMAIL,
        subject: `Order Confirmed — ${order.order_number}`,
        html,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      return { sent: false, error: `Resend API error (${res.status}): ${body}` };
    }
    return { sent: true };
  } catch (err) {
    return { sent: false, error: err instanceof Error ? err.message : 'Unknown email error' };
  }
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));
}

// ── Email-verified welcome email ──────────────────────────────────
// Sent exactly once, server-side, the moment a user's email_confirmed_at
// transitions from null to a real timestamp — see
// supabase/migration_email_verification_webhook.sql for the trigger
// that calls the on-email-verified function, which calls this. Not
// triggered from the client, so it fires reliably even if the person
// closes the tab right after clicking the verification link.
export async function sendVerificationWelcomeEmail({
  toEmail, toName,
}: {
  toEmail: string;
  toName?: string | null;
}): Promise<{ sent: boolean; error?: string }> {
  if (!RESEND_API_KEY) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const html = `
  <div style="font-family:Arial,sans-serif;max-width:520px;margin:0 auto;color:#111;">
    <h1 style="font-size:20px;letter-spacing:-0.02em;">RacquetIn</h1>
    <p style="font-size:15px;">Hi ${toName ? escapeHtml(toName) : 'there'},</p>
    <p style="font-size:15px;">Your email is verified and your account is ready to go.</p>
    <p style="font-size:15px;">Browse the collection, track orders, and manage your wishlist — all from your account.</p>
    <p style="font-size:13px;color:#666;margin-top:32px;">Questions? Just reply to this email.</p>
  </div>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: toEmail,
        reply_to: REPLY_TO_EMAIL,
        subject: 'Welcome to RacquetIn — you\'re verified',
        html,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      return { sent: false, error: `Resend API error (${res.status}): ${body}` };
    }
    return { sent: true };
  } catch (err) {
    return { sent: false, error: err instanceof Error ? err.message : 'Unknown email error' };
  }
}

// ═══ inlined: _shared/fulfillOrder.ts ═══
// ── Shared order fulfillment ──────────────────────────────────────
// Called after a payment is confirmed captured (either via the
// client-driven verify-razorpay-payment call, or via the
// razorpay-webhook as a safety net if the client never completes
// that call — e.g. the customer closed the tab right after paying).
// Idempotent: if the intent has already been consumed, this is a
// no-op that returns the existing order instead of creating a
// duplicate — Razorpay webhooks and client verification can both
// arrive for the same payment, sometimes more than once.


export async function fulfillOrderFromIntent({
  admin, providerOrderId, providerPaymentId, paymentMethod, rawPayment,
}: {
  admin: SupabaseClient;
  providerOrderId: string;
  providerPaymentId: string;
  paymentMethod?: string | null;
  rawPayment: unknown;
}): Promise<{ order: any; alreadyFulfilled: boolean; error: string | null; emailSent?: boolean; emailError?: string | null }> {
  const { data: intent, error: intentError } = await admin
    .from('payment_intents')
    .select('*')
    .eq('provider_order_id', providerOrderId)
    .maybeSingle();

  if (intentError) return { order: null, alreadyFulfilled: false, error: intentError.message };
  if (!intent) return { order: null, alreadyFulfilled: false, error: 'No matching payment intent for this order id' };

  // Already fulfilled — return the existing order instead of creating a duplicate.
  if (intent.status === 'consumed') {
    const { data: existingPayment } = await admin
      .from('payments')
      .select('order_id')
      .eq('provider_order_id', providerOrderId)
      .maybeSingle();
    if (existingPayment?.order_id) {
      const { data: existingOrder } = await admin.from('orders').select('*').eq('id', existingPayment.order_id).single();
      return { order: existingOrder, alreadyFulfilled: true, error: null };
    }
    return { order: null, alreadyFulfilled: true, error: null };
  }

  // 1. Create the real order from the server-computed intent snapshot —
  //    never from anything the client sends at this step.
  const { data: order, error: orderError } = await admin
    .from('orders')
    .insert([{
      user_id: intent.user_id,
      status: 'pending',
      payment_status: 'paid',
      payment_id: providerPaymentId,
      razorpay_order_id: providerOrderId,
      payment_verified: true,
      payment_method: paymentMethod || null,
      subtotal: intent.subtotal,
      tax: intent.tax,
      shipping_cost: intent.shipping_cost,
      discount: intent.discount,
      total: intent.total,
      shipping_address: intent.shipping_address,
      billing_address: intent.billing_address || intent.shipping_address,
      coupon_code: intent.coupon_code,
    }])
    .select().single();

  if (orderError) return { order: null, alreadyFulfilled: false, error: orderError.message };

  // 2. Order items, from the same snapshot.
  const items = intent.items as Array<{ product_id: string | null; name: string; price: number; qty: number; variant?: object; variant_id?: string | null; image_url?: string | null }>;
  const orderItems = items.map(i => ({
    order_id: order.id,
    product_id: i.product_id,
    name: i.name,
    price: i.price,
    qty: i.qty,
    variant: i.variant || {},
    variant_id: i.variant_id || null,
    image_url: i.image_url || null,
  }));
  const { error: itemsError } = await admin.from('order_items').insert(orderItems);
  if (itemsError) return { order, alreadyFulfilled: false, error: itemsError.message };

  // 3. Inventory — decremented only now, never before verified payment.
  // A line with a variant_id (e.g. a specific shoe size) deducts from
  // that variant's own tracked stock, not the parent product's — the
  // whole reason product_variants exists rather than a single stock
  // number per product.
  for (const item of items) {
    if (item.variant_id) {
      await admin.rpc('decrement_variant_stock', { variant_id: item.variant_id, qty: item.qty });
    } else if (item.product_id) {
      await admin.rpc('decrement_stock', { product_id: item.product_id, qty: item.qty });
    }
  }

  // 4. Payment record.
  const { error: paymentError } = await admin
    .from('payments')
    .insert([{
      order_id: order.id,
      customer_id: intent.user_id,
      provider: 'razorpay',
      provider_order_id: providerOrderId,
      provider_payment_id: providerPaymentId,
      amount: intent.total,
      currency: 'INR',
      status: 'paid',
      signature_verified: true,
      payment_method: paymentMethod || null,
      captured_at: new Date().toISOString(),
      raw_response: rawPayment,
    }]);
  if (paymentError) return { order, alreadyFulfilled: false, error: paymentError.message };

  // 5. Shipment placeholder + its first timeline event.
  const { data: shipment } = await admin
    .from('shipments')
    .insert([{ order_id: order.id, provider: 'manual', shipment_status: 'pending' }])
    .select().single();
  if (shipment) {
    await admin.from('shipment_events').insert([{
      shipment_id: shipment.id,
      event_type: 'pending',
      description: 'Order confirmed — preparing for dispatch.',
    }]);
  }

  // 6. Clear the cart server-side (the client also clears its own local
  //    state on success, but doing it here too means the cart is empty
  //    even if the client never gets to run that code).
  await admin.from('cart_items').delete().eq('user_id', intent.user_id);

  // 7. Mark the intent consumed so a duplicate webhook/verify call is a no-op.
  await admin.from('payment_intents').update({ status: 'consumed', consumed_at: new Date().toISOString() }).eq('id', intent.id);

  // 8. Order confirmation email — best-effort only. A failed send here
  // must never undo or fail the order itself; the order has already
  // been created, paid, and inventory adjusted by this point. It IS,
  // however, logged and returned to the caller — a previous version of
  // this swallowed every failure completely silently (no log, no
  // return value), which made "customer says they never got an email"
  // impossible to diagnose from the Edge Function logs alone.
  let emailSent = false;
  let emailError: string | null = null;
  try {
    const { data: customer, error: customerError } = await admin
      .from('customers')
      .select('email, full_name')
      .eq('user_id', intent.user_id)
      .maybeSingle();

    if (customerError) {
      emailError = `Could not look up customer: ${customerError.message}`;
    } else if (!customer?.email) {
      emailError = `No customers row (or no email on it) for user_id ${intent.user_id}`;
    } else {
      const result = await sendOrderConfirmationEmail({
        toEmail: customer.email,
        toName: customer.full_name,
        order: { order_number: order.order_number, total: order.total, payment_method: paymentMethod, created_at: order.created_at },
        items: items.map(i => ({ name: i.name, price: i.price, qty: i.qty })),
      });
      emailSent = result.sent;
      emailError = result.error || null;
    }
  } catch (err) {
    emailError = err instanceof Error ? err.message : 'Unknown error sending order confirmation email';
  }

  if (!emailSent) {
    console.error(`[fulfillOrder] order confirmation email NOT sent for order ${order.order_number}: ${emailError}`);
  } else {
    console.log(`[fulfillOrder] order confirmation email sent for order ${order.order_number}`);
  }

  return { order, alreadyFulfilled: false, error: null, emailSent, emailError };
}

// ═══ verify-razorpay-payment/index.ts (entry point) ═══
// ── verify-razorpay-payment ───────────────────────────────────────
// POST body: { razorpay_payment_id, razorpay_order_id, razorpay_signature }
// Requires: Authorization: Bearer <user's Supabase access token>
//
// This is the ONLY place an order is allowed to be created. Steps:
//   1. Recompute the HMAC signature server-side and compare — reject
//      immediately on any mismatch.
//   2. Re-fetch the payment from Razorpay's API directly (not trusting
//      the client's response object) to confirm it's actually captured
//      and its amount matches what we quoted.
//   3. Only then: create the order from the stored payment_intent,
//      decrement inventory, record the payment, create a shipment
//      placeholder, and clear the cart.




Deno.serve(async (req) => {
  const opt = handleOptions(req);
  if (opt) return opt;
  if (req.method !== 'POST') return jsonResponse({ error: 'Method not allowed' }, 405);

  try {
    const { user, error: authError } = await getRequestUser(req);
    if (!user) return jsonResponse({ error: authError || 'Not authenticated' }, 401);

    const body = await req.json();
    const { razorpay_payment_id, razorpay_order_id, razorpay_signature } = body || {};
    if (!razorpay_payment_id || !razorpay_order_id || !razorpay_signature) {
      return jsonResponse({ error: 'Missing payment verification fields' }, 400);
    }

    // 1. Signature check — reject immediately, do not touch the DB at all
    //    if this fails. This is the line that stops a forged/replayed
    //    "success" from ever reaching order creation.
    const validSignature = await verifyCheckoutSignature({
      orderId: razorpay_order_id,
      paymentId: razorpay_payment_id,
      signature: razorpay_signature,
    });
    if (!validSignature) {
      return jsonResponse({ error: 'Payment signature verification failed' }, 400);
    }

    const admin = getAdminClient();

    // Ownership check: the payment_intent for this order id must
    // belong to the authenticated caller — stops one user from
    // verifying (and fulfilling) another user's order id.
    const { data: intent } = await admin
      .from('payment_intents')
      .select('user_id')
      .eq('provider_order_id', razorpay_order_id)
      .maybeSingle();
    if (!intent) return jsonResponse({ error: 'No matching order found for this payment' }, 404);
    if (intent.user_id !== user.id) return jsonResponse({ error: 'This payment does not belong to your account' }, 403);

    // 2. Re-confirm with Razorpay directly — belt and suspenders beyond
    //    the signature check, per Razorpay's own recommendation.
    const payment = await fetchRazorpayPayment(razorpay_payment_id);
    if (payment.order_id !== razorpay_order_id) {
      return jsonResponse({ error: 'Payment/order mismatch' }, 400);
    }
    if (payment.status !== 'captured' && payment.status !== 'authorized') {
      return jsonResponse({ error: `Payment not completed (status: ${payment.status})` }, 400);
    }

    // 3. Fulfill — idempotent, safe even if the webhook already did this.
    const { order, alreadyFulfilled, error: fulfillError, emailSent, emailError } = await fulfillOrderFromIntent({
      admin,
      providerOrderId: razorpay_order_id,
      providerPaymentId: razorpay_payment_id,
      paymentMethod: payment.method || null,
      rawPayment: payment,
    });

    if (fulfillError) return jsonResponse({ error: fulfillError }, 500);

    await admin.from('payment_events').insert([{
      payment_id: null,
      provider: 'razorpay',
      provider_order_id: razorpay_order_id,
      provider_payment_id: razorpay_payment_id,
      event_type: 'payment.verified_by_client',
      payload: payment,
      processed: true,
    }]);

    return jsonResponse({ success: true, alreadyFulfilled, order, emailSent, emailError });
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error' }, 500);
  }
});
